// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.9
// source: order/v1/order.proto

package orderv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrderInternalService_GetOrder_FullMethodName = "/tokobangunan.order.v1.OrderInternalService/GetOrder"
)

// OrderInternalServiceClient is the client API for OrderInternalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderInternalServiceClient interface {
	GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderResponse, error)
}

type orderInternalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderInternalServiceClient(cc grpc.ClientConnInterface) OrderInternalServiceClient {
	return &orderInternalServiceClient{cc}
}

func (c *orderInternalServiceClient) GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrderResponse)
	err := c.cc.Invoke(ctx, OrderInternalService_GetOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderInternalServiceServer is the server API for OrderInternalService service.
// All implementations must embed UnimplementedOrderInternalServiceServer
// for forward compatibility.
type OrderInternalServiceServer interface {
	GetOrder(context.Context, *GetOrderRequest) (*GetOrderResponse, error)
	mustEmbedUnimplementedOrderInternalServiceServer()
}

// UnimplementedOrderInternalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderInternalServiceServer struct{}

func (UnimplementedOrderInternalServiceServer) GetOrder(context.Context, *GetOrderRequest) (*GetOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrder not implemented")
}
func (UnimplementedOrderInternalServiceServer) mustEmbedUnimplementedOrderInternalServiceServer() {}
func (UnimplementedOrderInternalServiceServer) testEmbeddedByValue()                              {}

// UnsafeOrderInternalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderInternalServiceServer will
// result in compilation errors.
type UnsafeOrderInternalServiceServer interface {
	mustEmbedUnimplementedOrderInternalServiceServer()
}

func RegisterOrderInternalServiceServer(s grpc.ServiceRegistrar, srv OrderInternalServiceServer) {
	// If the following call panics, it indicates UnimplementedOrderInternalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderInternalService_ServiceDesc, srv)
}

func _OrderInternalService_GetOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderInternalServiceServer).GetOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderInternalService_GetOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderInternalServiceServer).GetOrder(ctx, req.(*GetOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderInternalService_ServiceDesc is the grpc.ServiceDesc for OrderInternalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderInternalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tokobangunan.order.v1.OrderInternalService",
	HandlerType: (*OrderInternalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOrder",
			Handler:    _OrderInternalService_GetOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order/v1/order.proto",
}
