// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: inventory/v1/inventory.proto

package inventoryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestMetadata struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId  string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	CausationId    string                 `protobuf:"bytes,2,opt,name=causation_id,json=causationId,proto3" json:"causation_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RequestMetadata) Reset() {
	*x = RequestMetadata{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMetadata) ProtoMessage() {}

func (x *RequestMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMetadata.ProtoReflect.Descriptor instead.
func (*RequestMetadata) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *RequestMetadata) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *RequestMetadata) GetCausationId() string {
	if x != nil {
		return x.CausationId
	}
	return ""
}

func (x *RequestMetadata) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type ProductSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Unit          string                 `protobuf:"bytes,4,opt,name=unit,proto3" json:"unit,omitempty"`
	UnitPrice     int64                  `protobuf:"varint,5,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	AvailableQty  float64                `protobuf:"fixed64,6,opt,name=available_qty,json=availableQty,proto3" json:"available_qty,omitempty"`
	WeightKg      float64                `protobuf:"fixed64,7,opt,name=weight_kg,json=weightKg,proto3" json:"weight_kg,omitempty"`
	RequiresTruck bool                   `protobuf:"varint,8,opt,name=requires_truck,json=requiresTruck,proto3" json:"requires_truck,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductSnapshot) Reset() {
	*x = ProductSnapshot{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductSnapshot) ProtoMessage() {}

func (x *ProductSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductSnapshot.ProtoReflect.Descriptor instead.
func (*ProductSnapshot) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *ProductSnapshot) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ProductSnapshot) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductSnapshot) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ProductSnapshot) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *ProductSnapshot) GetUnitPrice() int64 {
	if x != nil {
		return x.UnitPrice
	}
	return 0
}

func (x *ProductSnapshot) GetAvailableQty() float64 {
	if x != nil {
		return x.AvailableQty
	}
	return 0
}

func (x *ProductSnapshot) GetWeightKg() float64 {
	if x != nil {
		return x.WeightKg
	}
	return 0
}

func (x *ProductSnapshot) GetRequiresTruck() bool {
	if x != nil {
		return x.RequiresTruck
	}
	return false
}

type OrderItemInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      float64                `protobuf:"fixed64,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItemInput) Reset() {
	*x = OrderItemInput{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItemInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItemInput) ProtoMessage() {}

func (x *OrderItemInput) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItemInput.ProtoReflect.Descriptor instead.
func (*OrderItemInput) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *OrderItemInput) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *OrderItemInput) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type ValidatedOrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductName   string                 `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	Unit          string                 `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	Quantity      float64                `protobuf:"fixed64,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPrice     int64                  `protobuf:"varint,5,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	LineTotal     int64                  `protobuf:"varint,6,opt,name=line_total,json=lineTotal,proto3" json:"line_total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatedOrderItem) Reset() {
	*x = ValidatedOrderItem{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatedOrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatedOrderItem) ProtoMessage() {}

func (x *ValidatedOrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatedOrderItem.ProtoReflect.Descriptor instead.
func (*ValidatedOrderItem) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *ValidatedOrderItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ValidatedOrderItem) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *ValidatedOrderItem) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *ValidatedOrderItem) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ValidatedOrderItem) GetUnitPrice() int64 {
	if x != nil {
		return x.UnitPrice
	}
	return 0
}

func (x *ValidatedOrderItem) GetLineTotal() int64 {
	if x != nil {
		return x.LineTotal
	}
	return 0
}

type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *GetProductRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GetProductRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type GetProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *ProductSnapshot       `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductResponse) Reset() {
	*x = GetProductResponse{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductResponse) ProtoMessage() {}

func (x *GetProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductResponse.ProtoReflect.Descriptor instead.
func (*GetProductResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *GetProductResponse) GetProduct() *ProductSnapshot {
	if x != nil {
		return x.Product
	}
	return nil
}

type ValidateProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Items         []*OrderItemInput      `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateProductsRequest) Reset() {
	*x = ValidateProductsRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateProductsRequest) ProtoMessage() {}

func (x *ValidateProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateProductsRequest.ProtoReflect.Descriptor instead.
func (*ValidateProductsRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{6}
}

func (x *ValidateProductsRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ValidateProductsRequest) GetItems() []*OrderItemInput {
	if x != nil {
		return x.Items
	}
	return nil
}

type ValidateProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ValidatedOrderItem  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	TotalAmount   int64                  `protobuf:"varint,2,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateProductsResponse) Reset() {
	*x = ValidateProductsResponse{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateProductsResponse) ProtoMessage() {}

func (x *ValidateProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateProductsResponse.ProtoReflect.Descriptor instead.
func (*ValidateProductsResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{7}
}

func (x *ValidateProductsResponse) GetItems() []*ValidatedOrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ValidateProductsResponse) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type ReserveStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Items         []*OrderItemInput      `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveStockRequest) Reset() {
	*x = ReserveStockRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveStockRequest) ProtoMessage() {}

func (x *ReserveStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveStockRequest.ProtoReflect.Descriptor instead.
func (*ReserveStockRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{8}
}

func (x *ReserveStockRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ReserveStockRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ReserveStockRequest) GetItems() []*OrderItemInput {
	if x != nil {
		return x.Items
	}
	return nil
}

type ReserveStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	FailureReason string                 `protobuf:"bytes,3,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveStockResponse) Reset() {
	*x = ReserveStockResponse{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveStockResponse) ProtoMessage() {}

func (x *ReserveStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveStockResponse.ProtoReflect.Descriptor instead.
func (*ReserveStockResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{9}
}

func (x *ReserveStockResponse) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *ReserveStockResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReserveStockResponse) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

type ReleaseStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseStockRequest) Reset() {
	*x = ReleaseStockRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseStockRequest) ProtoMessage() {}

func (x *ReleaseStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseStockRequest.ProtoReflect.Descriptor instead.
func (*ReleaseStockRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{10}
}

func (x *ReleaseStockRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ReleaseStockRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type ReleaseStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseStockResponse) Reset() {
	*x = ReleaseStockResponse{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseStockResponse) ProtoMessage() {}

func (x *ReleaseStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseStockResponse.ProtoReflect.Descriptor instead.
func (*ReleaseStockResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{11}
}

func (x *ReleaseStockResponse) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *ReleaseStockResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CommitStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitStockRequest) Reset() {
	*x = CommitStockRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitStockRequest) ProtoMessage() {}

func (x *CommitStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitStockRequest.ProtoReflect.Descriptor instead.
func (*CommitStockRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{12}
}

func (x *CommitStockRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CommitStockRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type CommitStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitStockResponse) Reset() {
	*x = CommitStockResponse{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitStockResponse) ProtoMessage() {}

func (x *CommitStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitStockResponse.ProtoReflect.Descriptor instead.
func (*CommitStockResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{13}
}

func (x *CommitStockResponse) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *CommitStockResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_inventory_v1_inventory_proto protoreflect.FileDescriptor

const file_inventory_v1_inventory_proto_rawDesc = "" +
	"\n" +
	"\x1cinventory/v1/inventory.proto\x12\x19tokobangunan.inventory.v1\"\x84\x01\n" +
	"\x0fRequestMetadata\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12!\n" +
	"\fcausation_id\x18\x02 \x01(\tR\vcausationId\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\"\xfc\x01\n" +
	"\x0fProductSnapshot\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x12\n" +
	"\x04unit\x18\x04 \x01(\tR\x04unit\x12\x1d\n" +
	"\n" +
	"unit_price\x18\x05 \x01(\x03R\tunitPrice\x12#\n" +
	"\ravailable_qty\x18\x06 \x01(\x01R\favailableQty\x12\x1b\n" +
	"\tweight_kg\x18\a \x01(\x01R\bweightKg\x12%\n" +
	"\x0erequires_truck\x18\b \x01(\bR\rrequiresTruck\"K\n" +
	"\x0eOrderItemInput\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x01R\bquantity\"\xc4\x01\n" +
	"\x12ValidatedOrderItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12!\n" +
	"\fproduct_name\x18\x02 \x01(\tR\vproductName\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\tR\x04unit\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x01R\bquantity\x12\x1d\n" +
	"\n" +
	"unit_price\x18\x05 \x01(\x03R\tunitPrice\x12\x1d\n" +
	"\n" +
	"line_total\x18\x06 \x01(\x03R\tlineTotal\"z\n" +
	"\x11GetProductRequest\x12F\n" +
	"\bmetadata\x18\x01 \x01(\v2*.tokobangunan.inventory.v1.RequestMetadataR\bmetadata\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\"Z\n" +
	"\x12GetProductResponse\x12D\n" +
	"\aproduct\x18\x01 \x01(\v2*.tokobangunan.inventory.v1.ProductSnapshotR\aproduct\"\xa2\x01\n" +
	"\x17ValidateProductsRequest\x12F\n" +
	"\bmetadata\x18\x01 \x01(\v2*.tokobangunan.inventory.v1.RequestMetadataR\bmetadata\x12?\n" +
	"\x05items\x18\x02 \x03(\v2).tokobangunan.inventory.v1.OrderItemInputR\x05items\"\x82\x01\n" +
	"\x18ValidateProductsResponse\x12C\n" +
	"\x05items\x18\x01 \x03(\v2-.tokobangunan.inventory.v1.ValidatedOrderItemR\x05items\x12!\n" +
	"\ftotal_amount\x18\x02 \x01(\x03R\vtotalAmount\"\xb9\x01\n" +
	"\x13ReserveStockRequest\x12F\n" +
	"\bmetadata\x18\x01 \x01(\v2*.tokobangunan.inventory.v1.RequestMetadataR\bmetadata\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12?\n" +
	"\x05items\x18\x03 \x03(\v2).tokobangunan.inventory.v1.OrderItemInputR\x05items\"|\n" +
	"\x14ReserveStockResponse\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12%\n" +
	"\x0efailure_reason\x18\x03 \x01(\tR\rfailureReason\"x\n" +
	"\x13ReleaseStockRequest\x12F\n" +
	"\bmetadata\x18\x01 \x01(\v2*.tokobangunan.inventory.v1.RequestMetadataR\bmetadata\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\"U\n" +
	"\x14ReleaseStockResponse\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"w\n" +
	"\x12CommitStockRequest\x12F\n" +
	"\bmetadata\x18\x01 \x01(\v2*.tokobangunan.inventory.v1.RequestMetadataR\bmetadata\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\"T\n" +
	"\x13CommitStockResponse\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2\xca\x04\n" +
	"\x10InventoryService\x12i\n" +
	"\n" +
	"GetProduct\x12,.tokobangunan.inventory.v1.GetProductRequest\x1a-.tokobangunan.inventory.v1.GetProductResponse\x12{\n" +
	"\x10ValidateProducts\x122.tokobangunan.inventory.v1.ValidateProductsRequest\x1a3.tokobangunan.inventory.v1.ValidateProductsResponse\x12o\n" +
	"\fReserveStock\x12..tokobangunan.inventory.v1.ReserveStockRequest\x1a/.tokobangunan.inventory.v1.ReserveStockResponse\x12o\n" +
	"\fReleaseStock\x12..tokobangunan.inventory.v1.ReleaseStockRequest\x1a/.tokobangunan.inventory.v1.ReleaseStockResponse\x12l\n" +
	"\vCommitStock\x12-.tokobangunan.inventory.v1.CommitStockRequest\x1a..tokobangunan.inventory.v1.CommitStockResponseBQZOgithub.com/odealidj/go-distributed-toko-bangunan/proto/inventory/v1;inventoryv1b\x06proto3"

var (
	file_inventory_v1_inventory_proto_rawDescOnce sync.Once
	file_inventory_v1_inventory_proto_rawDescData []byte
)

func file_inventory_v1_inventory_proto_rawDescGZIP() []byte {
	file_inventory_v1_inventory_proto_rawDescOnce.Do(func() {
		file_inventory_v1_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inventory_v1_inventory_proto_rawDesc), len(file_inventory_v1_inventory_proto_rawDesc)))
	})
	return file_inventory_v1_inventory_proto_rawDescData
}

var file_inventory_v1_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_inventory_v1_inventory_proto_goTypes = []any{
	(*RequestMetadata)(nil),          // 0: tokobangunan.inventory.v1.RequestMetadata
	(*ProductSnapshot)(nil),          // 1: tokobangunan.inventory.v1.ProductSnapshot
	(*OrderItemInput)(nil),           // 2: tokobangunan.inventory.v1.OrderItemInput
	(*ValidatedOrderItem)(nil),       // 3: tokobangunan.inventory.v1.ValidatedOrderItem
	(*GetProductRequest)(nil),        // 4: tokobangunan.inventory.v1.GetProductRequest
	(*GetProductResponse)(nil),       // 5: tokobangunan.inventory.v1.GetProductResponse
	(*ValidateProductsRequest)(nil),  // 6: tokobangunan.inventory.v1.ValidateProductsRequest
	(*ValidateProductsResponse)(nil), // 7: tokobangunan.inventory.v1.ValidateProductsResponse
	(*ReserveStockRequest)(nil),      // 8: tokobangunan.inventory.v1.ReserveStockRequest
	(*ReserveStockResponse)(nil),     // 9: tokobangunan.inventory.v1.ReserveStockResponse
	(*ReleaseStockRequest)(nil),      // 10: tokobangunan.inventory.v1.ReleaseStockRequest
	(*ReleaseStockResponse)(nil),     // 11: tokobangunan.inventory.v1.ReleaseStockResponse
	(*CommitStockRequest)(nil),       // 12: tokobangunan.inventory.v1.CommitStockRequest
	(*CommitStockResponse)(nil),      // 13: tokobangunan.inventory.v1.CommitStockResponse
}
var file_inventory_v1_inventory_proto_depIdxs = []int32{
	0,  // 0: tokobangunan.inventory.v1.GetProductRequest.metadata:type_name -> tokobangunan.inventory.v1.RequestMetadata
	1,  // 1: tokobangunan.inventory.v1.GetProductResponse.product:type_name -> tokobangunan.inventory.v1.ProductSnapshot
	0,  // 2: tokobangunan.inventory.v1.ValidateProductsRequest.metadata:type_name -> tokobangunan.inventory.v1.RequestMetadata
	2,  // 3: tokobangunan.inventory.v1.ValidateProductsRequest.items:type_name -> tokobangunan.inventory.v1.OrderItemInput
	3,  // 4: tokobangunan.inventory.v1.ValidateProductsResponse.items:type_name -> tokobangunan.inventory.v1.ValidatedOrderItem
	0,  // 5: tokobangunan.inventory.v1.ReserveStockRequest.metadata:type_name -> tokobangunan.inventory.v1.RequestMetadata
	2,  // 6: tokobangunan.inventory.v1.ReserveStockRequest.items:type_name -> tokobangunan.inventory.v1.OrderItemInput
	0,  // 7: tokobangunan.inventory.v1.ReleaseStockRequest.metadata:type_name -> tokobangunan.inventory.v1.RequestMetadata
	0,  // 8: tokobangunan.inventory.v1.CommitStockRequest.metadata:type_name -> tokobangunan.inventory.v1.RequestMetadata
	4,  // 9: tokobangunan.inventory.v1.InventoryService.GetProduct:input_type -> tokobangunan.inventory.v1.GetProductRequest
	6,  // 10: tokobangunan.inventory.v1.InventoryService.ValidateProducts:input_type -> tokobangunan.inventory.v1.ValidateProductsRequest
	8,  // 11: tokobangunan.inventory.v1.InventoryService.ReserveStock:input_type -> tokobangunan.inventory.v1.ReserveStockRequest
	10, // 12: tokobangunan.inventory.v1.InventoryService.ReleaseStock:input_type -> tokobangunan.inventory.v1.ReleaseStockRequest
	12, // 13: tokobangunan.inventory.v1.InventoryService.CommitStock:input_type -> tokobangunan.inventory.v1.CommitStockRequest
	5,  // 14: tokobangunan.inventory.v1.InventoryService.GetProduct:output_type -> tokobangunan.inventory.v1.GetProductResponse
	7,  // 15: tokobangunan.inventory.v1.InventoryService.ValidateProducts:output_type -> tokobangunan.inventory.v1.ValidateProductsResponse
	9,  // 16: tokobangunan.inventory.v1.InventoryService.ReserveStock:output_type -> tokobangunan.inventory.v1.ReserveStockResponse
	11, // 17: tokobangunan.inventory.v1.InventoryService.ReleaseStock:output_type -> tokobangunan.inventory.v1.ReleaseStockResponse
	13, // 18: tokobangunan.inventory.v1.InventoryService.CommitStock:output_type -> tokobangunan.inventory.v1.CommitStockResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_inventory_v1_inventory_proto_init() }
func file_inventory_v1_inventory_proto_init() {
	if File_inventory_v1_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inventory_v1_inventory_proto_rawDesc), len(file_inventory_v1_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inventory_v1_inventory_proto_goTypes,
		DependencyIndexes: file_inventory_v1_inventory_proto_depIdxs,
		MessageInfos:      file_inventory_v1_inventory_proto_msgTypes,
	}.Build()
	File_inventory_v1_inventory_proto = out.File
	file_inventory_v1_inventory_proto_goTypes = nil
	file_inventory_v1_inventory_proto_depIdxs = nil
}
