// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID       string
	Name     string
	IsActive bool
}

type InboxEvent struct {
	EventID       string
	EventType     string
	AggregateID   string
	CorrelationID string
	Traceparent   pgtype.Text
	ProcessedAt   pgtype.Timestamptz
}

type Inventory struct {
	ProductID   string
	OnHandQty   float64
	ReservedQty float64
	UpdatedAt   pgtype.Timestamptz
}

type OutboxEvent struct {
	ID            string
	AggregateID   string
	AggregateType string
	EventType     string
	CorrelationID string
	CausationID   pgtype.Text
	Traceparent   pgtype.Text
	Payload       []byte
	Status        string
	RetryCount    int32
	CreatedAt     pgtype.Timestamptz
	PublishedAt   pgtype.Timestamptz
}

type Product struct {
	ID            string
	CategoryID    string
	Sku           string
	Name          string
	Brand         pgtype.Text
	Unit          string
	Price         int64
	WeightKg      pgtype.Numeric
	RequiresTruck bool
	IsActive      bool
}

type StockReservation struct {
	ID             string
	OrderID        string
	Status         string
	IdempotencyKey string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type StockReservationItem struct {
	ID            string
	ReservationID string
	ProductID     string
	Quantity      float64
}
