// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package sqlc

import (
	"context"
)

const countProducts = `-- name: CountProducts :one
SELECT count(*)::int
FROM products p
JOIN categories c ON c.id = p.category_id
WHERE p.is_active = true
  AND c.is_active = true
  AND ($1::text = '' OR p.category_id = $1::text)
  AND ($2::text = '' OR p.name ILIKE '%' || $2::text || '%' OR p.sku ILIKE '%' || $2::text || '%')
`

type CountProductsParams struct {
	CategoryID string
	Search     string
}

func (q *Queries) CountProducts(ctx context.Context, arg CountProductsParams) (int32, error) {
	row := q.db.QueryRow(ctx, countProducts, arg.CategoryID, arg.Search)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getProduct = `-- name: GetProduct :one
SELECT
    p.id,
    p.category_id,
    c.name AS category_name,
    p.sku,
    p.name,
    COALESCE(p.brand, '')::text AS brand,
    p.unit,
    p.price,
    COALESCE(p.weight_kg, 0)::numeric AS weight_kg,
    p.requires_truck,
    (i.on_hand_qty - i.reserved_qty)::numeric AS available_qty
FROM products p
JOIN categories c ON c.id = p.category_id
JOIN inventories i ON i.product_id = p.id
WHERE p.id = $1
  AND p.is_active = true
  AND c.is_active = true
`

type GetProductRow struct {
	ID            string
	CategoryID    string
	CategoryName  string
	Sku           string
	Name          string
	Brand         string
	Unit          string
	Price         int64
	WeightKg      float64
	RequiresTruck bool
	AvailableQty  float64
}

func (q *Queries) GetProduct(ctx context.Context, id string) (GetProductRow, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i GetProductRow
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.CategoryName,
		&i.Sku,
		&i.Name,
		&i.Brand,
		&i.Unit,
		&i.Price,
		&i.WeightKg,
		&i.RequiresTruck,
		&i.AvailableQty,
	)
	return i, err
}

const getProductsByIDs = `-- name: GetProductsByIDs :many
SELECT
    p.id,
    p.name,
    p.unit,
    p.price,
    (i.on_hand_qty - i.reserved_qty)::numeric AS available_qty
FROM products p
JOIN inventories i ON i.product_id = p.id
WHERE p.id = ANY($1::text[])
  AND p.is_active = true
ORDER BY p.id ASC
`

type GetProductsByIDsRow struct {
	ID           string
	Name         string
	Unit         string
	Price        int64
	AvailableQty float64
}

func (q *Queries) GetProductsByIDs(ctx context.Context, dollar_1 []string) ([]GetProductsByIDsRow, error) {
	rows, err := q.db.Query(ctx, getProductsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductsByIDsRow
	for rows.Next() {
		var i GetProductsByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Unit,
			&i.Price,
			&i.AvailableQty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT
    p.id,
    p.category_id,
    c.name AS category_name,
    p.sku,
    p.name,
    COALESCE(p.brand, '')::text AS brand,
    p.unit,
    p.price,
    COALESCE(p.weight_kg, 0)::numeric AS weight_kg,
    p.requires_truck,
    (i.on_hand_qty - i.reserved_qty)::numeric AS available_qty
FROM products p
JOIN categories c ON c.id = p.category_id
JOIN inventories i ON i.product_id = p.id
WHERE p.is_active = true
  AND c.is_active = true
  AND ($1::text = '' OR p.category_id = $1::text)
  AND ($2::text = '' OR p.name ILIKE '%' || $2::text || '%' OR p.sku ILIKE '%' || $2::text || '%')
ORDER BY p.name ASC
LIMIT $4::int
OFFSET $3::int
`

type ListProductsParams struct {
	CategoryID string
	Search     string
	OffsetRows int32
	LimitRows  int32
}

type ListProductsRow struct {
	ID            string
	CategoryID    string
	CategoryName  string
	Sku           string
	Name          string
	Brand         string
	Unit          string
	Price         int64
	WeightKg      float64
	RequiresTruck bool
	AvailableQty  float64
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts,
		arg.CategoryID,
		arg.Search,
		arg.OffsetRows,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsRow
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.CategoryName,
			&i.Sku,
			&i.Name,
			&i.Brand,
			&i.Unit,
			&i.Price,
			&i.WeightKg,
			&i.RequiresTruck,
			&i.AvailableQty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
