// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reservations.sql

package sqlc

import (
	"context"
)

const addReservedStock = `-- name: AddReservedStock :exec
UPDATE inventories
SET reserved_qty = reserved_qty + $1::numeric,
    updated_at = now()
WHERE product_id = $2::text
`

type AddReservedStockParams struct {
	Quantity  float64
	ProductID string
}

func (q *Queries) AddReservedStock(ctx context.Context, arg AddReservedStockParams) error {
	_, err := q.db.Exec(ctx, addReservedStock, arg.Quantity, arg.ProductID)
	return err
}

const commitReservedStock = `-- name: CommitReservedStock :exec
UPDATE inventories
SET on_hand_qty = on_hand_qty - $1::numeric,
    reserved_qty = reserved_qty - $1::numeric,
    updated_at = now()
WHERE product_id = $2::text
`

type CommitReservedStockParams struct {
	Quantity  float64
	ProductID string
}

func (q *Queries) CommitReservedStock(ctx context.Context, arg CommitReservedStockParams) error {
	_, err := q.db.Exec(ctx, commitReservedStock, arg.Quantity, arg.ProductID)
	return err
}

const createReservation = `-- name: CreateReservation :one
INSERT INTO stock_reservations (id, order_id, status, idempotency_key)
VALUES ($1, $2, $3, $4)
RETURNING id, order_id, status, idempotency_key
`

type CreateReservationParams struct {
	ID             string
	OrderID        string
	Status         string
	IdempotencyKey string
}

type CreateReservationRow struct {
	ID             string
	OrderID        string
	Status         string
	IdempotencyKey string
}

func (q *Queries) CreateReservation(ctx context.Context, arg CreateReservationParams) (CreateReservationRow, error) {
	row := q.db.QueryRow(ctx, createReservation,
		arg.ID,
		arg.OrderID,
		arg.Status,
		arg.IdempotencyKey,
	)
	var i CreateReservationRow
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Status,
		&i.IdempotencyKey,
	)
	return i, err
}

const createReservationItem = `-- name: CreateReservationItem :exec
INSERT INTO stock_reservation_items (id, reservation_id, product_id, quantity)
VALUES ($1, $2, $3, $4)
`

type CreateReservationItemParams struct {
	ID            string
	ReservationID string
	ProductID     string
	Quantity      float64
}

func (q *Queries) CreateReservationItem(ctx context.Context, arg CreateReservationItemParams) error {
	_, err := q.db.Exec(ctx, createReservationItem,
		arg.ID,
		arg.ReservationID,
		arg.ProductID,
		arg.Quantity,
	)
	return err
}

const getReservationByIdempotencyKey = `-- name: GetReservationByIdempotencyKey :one
SELECT id, order_id, status, idempotency_key
FROM stock_reservations
WHERE idempotency_key = $1
`

type GetReservationByIdempotencyKeyRow struct {
	ID             string
	OrderID        string
	Status         string
	IdempotencyKey string
}

func (q *Queries) GetReservationByIdempotencyKey(ctx context.Context, idempotencyKey string) (GetReservationByIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getReservationByIdempotencyKey, idempotencyKey)
	var i GetReservationByIdempotencyKeyRow
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Status,
		&i.IdempotencyKey,
	)
	return i, err
}

const getReservationByOrderID = `-- name: GetReservationByOrderID :one
SELECT id, order_id, status, idempotency_key
FROM stock_reservations
WHERE order_id = $1
`

type GetReservationByOrderIDRow struct {
	ID             string
	OrderID        string
	Status         string
	IdempotencyKey string
}

func (q *Queries) GetReservationByOrderID(ctx context.Context, orderID string) (GetReservationByOrderIDRow, error) {
	row := q.db.QueryRow(ctx, getReservationByOrderID, orderID)
	var i GetReservationByOrderIDRow
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Status,
		&i.IdempotencyKey,
	)
	return i, err
}

const listReservationItems = `-- name: ListReservationItems :many
SELECT product_id, quantity
FROM stock_reservation_items
WHERE reservation_id = $1
ORDER BY product_id ASC
`

type ListReservationItemsRow struct {
	ProductID string
	Quantity  float64
}

func (q *Queries) ListReservationItems(ctx context.Context, reservationID string) ([]ListReservationItemsRow, error) {
	rows, err := q.db.Query(ctx, listReservationItems, reservationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReservationItemsRow
	for rows.Next() {
		var i ListReservationItemsRow
		if err := rows.Scan(&i.ProductID, &i.Quantity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockInventoriesForProducts = `-- name: LockInventoriesForProducts :many
SELECT product_id, on_hand_qty, reserved_qty
FROM inventories
WHERE product_id = ANY($1::text[])
FOR UPDATE
`

type LockInventoriesForProductsRow struct {
	ProductID   string
	OnHandQty   float64
	ReservedQty float64
}

func (q *Queries) LockInventoriesForProducts(ctx context.Context, dollar_1 []string) ([]LockInventoriesForProductsRow, error) {
	rows, err := q.db.Query(ctx, lockInventoriesForProducts, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LockInventoriesForProductsRow
	for rows.Next() {
		var i LockInventoriesForProductsRow
		if err := rows.Scan(&i.ProductID, &i.OnHandQty, &i.ReservedQty); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseReservedStock = `-- name: ReleaseReservedStock :exec
UPDATE inventories
SET reserved_qty = reserved_qty - $1::numeric,
    updated_at = now()
WHERE product_id = $2::text
`

type ReleaseReservedStockParams struct {
	Quantity  float64
	ProductID string
}

func (q *Queries) ReleaseReservedStock(ctx context.Context, arg ReleaseReservedStockParams) error {
	_, err := q.db.Exec(ctx, releaseReservedStock, arg.Quantity, arg.ProductID)
	return err
}

const updateReservationStatus = `-- name: UpdateReservationStatus :one
UPDATE stock_reservations
SET status = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, order_id, status, idempotency_key
`

type UpdateReservationStatusParams struct {
	ID     string
	Status string
}

type UpdateReservationStatusRow struct {
	ID             string
	OrderID        string
	Status         string
	IdempotencyKey string
}

func (q *Queries) UpdateReservationStatus(ctx context.Context, arg UpdateReservationStatusParams) (UpdateReservationStatusRow, error) {
	row := q.db.QueryRow(ctx, updateReservationStatus, arg.ID, arg.Status)
	var i UpdateReservationStatusRow
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Status,
		&i.IdempotencyKey,
	)
	return i, err
}
