// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type InboxEvent struct {
	EventID       string
	EventType     string
	AggregateID   string
	CorrelationID string
	Traceparent   pgtype.Text
	ProcessedAt   pgtype.Timestamptz
}

type Order struct {
	ID              string
	CustomerName    string
	CustomerPhone   string
	CustomerAddress pgtype.Text
	Status          string
	TotalAmount     int64
	PaymentID       pgtype.Text
	CorrelationID   string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type OrderItem struct {
	ID          string
	OrderID     string
	ProductID   string
	ProductName string
	Unit        string
	Quantity    pgtype.Numeric
	UnitPrice   int64
	LineTotal   int64
}

type OutboxEvent struct {
	ID            string
	AggregateID   string
	AggregateType string
	EventType     string
	CorrelationID string
	CausationID   pgtype.Text
	Traceparent   pgtype.Text
	Payload       []byte
	Status        string
	RetryCount    int32
	CreatedAt     pgtype.Timestamptz
	PublishedAt   pgtype.Timestamptz
}

type SagaInstance struct {
	ID            string
	OrderID       string
	Status        string
	CurrentStep   string
	CorrelationID string
	StartedAt     pgtype.Timestamptz
	CompletedAt   pgtype.Timestamptz
}

type SagaStep struct {
	ID             string
	SagaID         string
	StepName       string
	Status         string
	IdempotencyKey string
	ErrorMessage   pgtype.Text
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}
