// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOrders = `-- name: CountOrders :one
SELECT count(*)
FROM orders
WHERE ($1::text = '' OR status = $1)
`

func (q *Queries) CountOrders(ctx context.Context, dollar_1 string) (int64, error) {
	row := q.db.QueryRow(ctx, countOrders, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrder = `-- name: CreateOrder :exec
INSERT INTO orders (id, customer_name, customer_phone, customer_address, status, total_amount, payment_id, correlation_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateOrderParams struct {
	ID              string
	CustomerName    string
	CustomerPhone   string
	CustomerAddress pgtype.Text
	Status          string
	TotalAmount     int64
	PaymentID       pgtype.Text
	CorrelationID   string
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) error {
	_, err := q.db.Exec(ctx, createOrder,
		arg.ID,
		arg.CustomerName,
		arg.CustomerPhone,
		arg.CustomerAddress,
		arg.Status,
		arg.TotalAmount,
		arg.PaymentID,
		arg.CorrelationID,
	)
	return err
}

const createOrderItem = `-- name: CreateOrderItem :exec
INSERT INTO order_items (id, order_id, product_id, product_name, unit, quantity, unit_price, line_total)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateOrderItemParams struct {
	ID          string
	OrderID     string
	ProductID   string
	ProductName string
	Unit        string
	Quantity    pgtype.Numeric
	UnitPrice   int64
	LineTotal   int64
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) error {
	_, err := q.db.Exec(ctx, createOrderItem,
		arg.ID,
		arg.OrderID,
		arg.ProductID,
		arg.ProductName,
		arg.Unit,
		arg.Quantity,
		arg.UnitPrice,
		arg.LineTotal,
	)
	return err
}

const createOutboxEvent = `-- name: CreateOutboxEvent :exec
INSERT INTO outbox_events (id, aggregate_id, aggregate_type, event_type, correlation_id, causation_id, traceparent, payload, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateOutboxEventParams struct {
	ID            string
	AggregateID   string
	AggregateType string
	EventType     string
	CorrelationID string
	CausationID   pgtype.Text
	Traceparent   pgtype.Text
	Payload       []byte
	Status        string
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) error {
	_, err := q.db.Exec(ctx, createOutboxEvent,
		arg.ID,
		arg.AggregateID,
		arg.AggregateType,
		arg.EventType,
		arg.CorrelationID,
		arg.CausationID,
		arg.Traceparent,
		arg.Payload,
		arg.Status,
	)
	return err
}

const createSagaInstance = `-- name: CreateSagaInstance :exec
INSERT INTO saga_instances (id, order_id, status, current_step, correlation_id)
VALUES ($1, $2, $3, $4, $5)
`

type CreateSagaInstanceParams struct {
	ID            string
	OrderID       string
	Status        string
	CurrentStep   string
	CorrelationID string
}

func (q *Queries) CreateSagaInstance(ctx context.Context, arg CreateSagaInstanceParams) error {
	_, err := q.db.Exec(ctx, createSagaInstance,
		arg.ID,
		arg.OrderID,
		arg.Status,
		arg.CurrentStep,
		arg.CorrelationID,
	)
	return err
}

const createSagaStep = `-- name: CreateSagaStep :exec
INSERT INTO saga_steps (id, saga_id, step_name, status, idempotency_key, error_message)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateSagaStepParams struct {
	ID             string
	SagaID         string
	StepName       string
	Status         string
	IdempotencyKey string
	ErrorMessage   pgtype.Text
}

func (q *Queries) CreateSagaStep(ctx context.Context, arg CreateSagaStepParams) error {
	_, err := q.db.Exec(ctx, createSagaStep,
		arg.ID,
		arg.SagaID,
		arg.StepName,
		arg.Status,
		arg.IdempotencyKey,
		arg.ErrorMessage,
	)
	return err
}

const getOrder = `-- name: GetOrder :one
SELECT id, customer_name, customer_phone, customer_address, status, total_amount, payment_id, correlation_id
       , created_at, updated_at
FROM orders
WHERE id = $1
`

func (q *Queries) GetOrder(ctx context.Context, id string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.CustomerAddress,
		&i.Status,
		&i.TotalAmount,
		&i.PaymentID,
		&i.CorrelationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSagaInstanceByOrderID = `-- name: GetSagaInstanceByOrderID :one
SELECT id, order_id, status, current_step, correlation_id, completed_at
FROM saga_instances
WHERE order_id = $1
`

type GetSagaInstanceByOrderIDRow struct {
	ID            string
	OrderID       string
	Status        string
	CurrentStep   string
	CorrelationID string
	CompletedAt   pgtype.Timestamptz
}

func (q *Queries) GetSagaInstanceByOrderID(ctx context.Context, orderID string) (GetSagaInstanceByOrderIDRow, error) {
	row := q.db.QueryRow(ctx, getSagaInstanceByOrderID, orderID)
	var i GetSagaInstanceByOrderIDRow
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Status,
		&i.CurrentStep,
		&i.CorrelationID,
		&i.CompletedAt,
	)
	return i, err
}

const listOrderItems = `-- name: ListOrderItems :many
SELECT id, order_id, product_id, product_name, unit, quantity, unit_price, line_total
FROM order_items
WHERE order_id = $1
ORDER BY id
`

func (q *Queries) ListOrderItems(ctx context.Context, orderID string) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.ProductName,
			&i.Unit,
			&i.Quantity,
			&i.UnitPrice,
			&i.LineTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrders = `-- name: ListOrders :many
SELECT id, customer_name, customer_phone, customer_address, status, total_amount, payment_id, correlation_id
       , created_at, updated_at
FROM orders
WHERE ($1::text = '' OR status = $1)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListOrdersParams struct {
	Column1 string
	Limit   int32
	Offset  int32
}

func (q *Queries) ListOrders(ctx context.Context, arg ListOrdersParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrders, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.CustomerName,
			&i.CustomerPhone,
			&i.CustomerAddress,
			&i.Status,
			&i.TotalAmount,
			&i.PaymentID,
			&i.CorrelationID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders
SET status = $2, updated_at = now()
WHERE id = $1
`

type UpdateOrderStatusParams struct {
	ID     string
	Status string
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.Exec(ctx, updateOrderStatus, arg.ID, arg.Status)
	return err
}

const updateOrderStatusWithPayment = `-- name: UpdateOrderStatusWithPayment :exec
UPDATE orders
SET status = $2, payment_id = $3, updated_at = now()
WHERE id = $1
`

type UpdateOrderStatusWithPaymentParams struct {
	ID        string
	Status    string
	PaymentID pgtype.Text
}

func (q *Queries) UpdateOrderStatusWithPayment(ctx context.Context, arg UpdateOrderStatusWithPaymentParams) error {
	_, err := q.db.Exec(ctx, updateOrderStatusWithPayment, arg.ID, arg.Status, arg.PaymentID)
	return err
}

const updateSagaInstance = `-- name: UpdateSagaInstance :exec
UPDATE saga_instances
SET status = $2,
    current_step = $3,
    completed_at = CASE WHEN $4::boolean THEN now() ELSE completed_at END
WHERE order_id = $1
`

type UpdateSagaInstanceParams struct {
	OrderID     string
	Status      string
	CurrentStep string
	Column4     bool
}

func (q *Queries) UpdateSagaInstance(ctx context.Context, arg UpdateSagaInstanceParams) error {
	_, err := q.db.Exec(ctx, updateSagaInstance,
		arg.OrderID,
		arg.Status,
		arg.CurrentStep,
		arg.Column4,
	)
	return err
}
