// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listPendingOutboxEvents = `-- name: ListPendingOutboxEvents :many
SELECT id, aggregate_id, aggregate_type, event_type, correlation_id, causation_id, traceparent, payload, status, created_at
FROM outbox_events
WHERE status = 'PENDING'
ORDER BY created_at ASC
LIMIT $1
`

type ListPendingOutboxEventsRow struct {
	ID            string
	AggregateID   string
	AggregateType string
	EventType     string
	CorrelationID string
	CausationID   pgtype.Text
	Traceparent   pgtype.Text
	Payload       []byte
	Status        string
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) ListPendingOutboxEvents(ctx context.Context, limit int32) ([]ListPendingOutboxEventsRow, error) {
	rows, err := q.db.Query(ctx, listPendingOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingOutboxEventsRow
	for rows.Next() {
		var i ListPendingOutboxEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.AggregateID,
			&i.AggregateType,
			&i.EventType,
			&i.CorrelationID,
			&i.CausationID,
			&i.Traceparent,
			&i.Payload,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxEventFailed = `-- name: MarkOutboxEventFailed :exec
UPDATE outbox_events
SET retry_count = retry_count + 1
WHERE id = $1
`

func (q *Queries) MarkOutboxEventFailed(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markOutboxEventFailed, id)
	return err
}

const markOutboxEventPublished = `-- name: MarkOutboxEventPublished :exec
UPDATE outbox_events
SET status = 'PUBLISHED',
    published_at = now()
WHERE id = $1
`

func (q *Queries) MarkOutboxEventPublished(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markOutboxEventPublished, id)
	return err
}
